# ETL Pipeline Configuration
pipeline:
  name: "Air Quality ETL Pipeline"
  version: "1.0.0"
  steps:
    - name: "DataExtractionStep"
      enabled: true
    - name: "DataTransformationStep"
      enabled: true
    - name: "DataMergingStep"
      enabled: true
    - name: "FeatureEngineeringStep"
      enabled: true
    - name: "DataCleaningStep"
      enabled: true
    - name: "DataValidationStep"
      enabled: true
    - name: "DataExportStep"
      enabled: true
    - name: "DataQualityReportStep"
      enabled: true

# Data Sources Configuration
data_sources:
  air_quality:
    format: "csv"
    data_directory: "air_quality_data"
    raw_file: "air_quality_with_province.csv"
    processed_file: "air_quality.csv"
    columns_to_use:
      - "Air Pollutant"
      - "Air Pollutant Description"
      - "Data Aggregation Process"
      - "Year"
      - "Air Pollution Level"
      - "Unit Of Air Pollution Level"
      - "Air Quality Station Type"
      - "Air Quality Station Area"
      - "Altitude"
      - "Longitude"
      - "Latitude"
      - "Province"

  health:
    format: "csv"
    data_directory: "health_data"
    respiratory_diseases_file: "enfermedades_respiratorias.csv"
    life_expectancy_file: "esperanza_vida.csv"
    processed_file: "health.csv"
    respiratory_separator: ";"
    respiratory_decimal: ","
    life_expectancy_separator: ";"
    life_expectancy_decimal: ","
    life_expectancy_encoding: "latin1"
    date_columns: ["Periodo"]

  socioeconomic:
    format: "csv"
    data_directory: "socioeconomic_data"
    gdp_file: "PIB per cap provincias 2000-2021.csv"
    population_file: "poblacion_provincias.csv"
    processed_gdp_file: "province_gdp.csv"
    processed_population_file: "province_population_size.csv"
    gdp_separator: ";"
    gdp_decimal: ","
    gdp_encoding: "ISO-8859-1"
    population_separator: ";"
    population_decimal: ","
    population_encoding: "latin1"
    date_columns: ["Periodo"]

# Processing Configuration
processing:
  time_range:
    start_year: 2000
    end_year: 2021

  data_quality:
    null_threshold_percent: 5.0
    allow_duplicates: false
    strict_validation: true

  excluded_regions:
    - "Santa Cruz de Tenerife"
    - "Las Palmas"
    - "Illes Balears"
    - "Ceuta"
    - "Melilla"

  air_quality:
    invalid_province_values:
      - "nan"
      - "Desconocido"
      - "Error"

# Output Configuration
output:
  directory: "output"
  formats: ["csv"]
  filename: "dataset.csv"
  reports_directory: "reports"
  quality_report_filename: "data_quality_report.json"

# Validation Configuration
validation:
  required_columns:
    - "Province"
    - "Year"
    - "Air Pollution Level"

  data_types:
    numeric_columns:
      - "Year"
      - "Air Pollution Level"
      - "Latitude"
      - "Longitude"
    categorical_columns:
      - "Province"
      - "Air Pollutant"
      - "Autonomous Community"

  ranges:
    Year:
      min: 2000
      max: 2021
    "Air Pollution Level":
      min: 0
      max: 1000

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_prefix: "etl_pipeline"
  max_files: 10
  max_file_size_mb: 50
